export default {
    Site: site,
    'Notes': 'Not Set',
    'Total Objects': 'Not Set',
    'Invalid Titles': 'Not Set',
    'Invalid Page Titles': 'Not Set',
    'Invalid Links': 'Not Set',
    'Invalid Images': 'Not Set',
    'Invalid Prices': 'Not Set',
    'Unset Prices': 'Not Set',
    'Price Scrape Errors': 'Not Set',
    'Product Not Available': 'Not Set',
    'Total Unique Objects (by link)': 'Not Set',
    'Error Objects': 'Not Set',
    "JSONErrorGit": 'Not Set',
    "JSONErrorDrive": 'Not Set',
    "JSONDataGit": 'Not Set',
    "JSONDataDrive": 'Not Set',
    'Start Time': 'Not Set',
    'End Time': 'Not Set',
    'Span (min)': 'Not Set',
    'Total Pages': 'Not Set',
    'Unique Page URLs': 'Not Set',
    'AutoScroll': 'Not Set',
    'productPageSelector': 'Not Set',
    'productItemSelector': 'Not Set',
    'ScreenshotGit': 'Not Set'

};