export default {
    'Site': 'N/A',
    'Notes': 'N/A',
    'Total Objects': 'N/A',
    'Invalid Titles': 'N/A',
    'Invalid Page Titles': 'N/A',
    'Invalid Links': 'N/A',
    'Invalid Images': 'N/A',
    'Invalid Prices': 'N/A',
    'Unset Prices': 'N/A',
    'Price Scrape Errors': 'N/A',
    'Product Not Available': 'N/A',
    'Total Unique Objects (by link)': 'N/A',
    'Error Objects': 'N/A',
    "JSONErrorGit": 'N/A',
    "JSONErrorDrive": 'N/A',
    "JSONDataGit": 'N/A',
    "JSONDataDrive": 'N/A',
    'Start Time': 'N/A',
    'End Time': 'N/A',
    'Span (min)': 'N/A',
    'Total Pages': 'N/A',
    'Unique Page URLs': 'N/A',
    'AutoScroll': 'N/A',
    'productPageSelector': 'N/A',
    'productItemSelector': 'N/A',
    'ScreenshotGit': 'N/A'

};