export default [
    "**login**",
    "**user**","auth",
    "basket",
    "facebook",
    "twitter",
    "instagram",
    "anasayfa",
    "checkout",
    "magazalar",
    "teslimat",
    "cart",
    "hakkimizda",
    "mesafeli-satis-sozlesmesi",
    "gizlilik",
    "tum-urunler",
    "erkek-giyim",
    "kadin-giyim",
    "genc-kadin-giyim",
    "bebek-anasayfa",
    "evcil-hayvan-kiyafetleri",
    "cocuk-tumu",
    "sosyal-sorumluluk",
    "lookbook"

]