export default [
  'img.category-products-image',
  '.image-inner img',
  '.ltb__product--image',
  '.product-image__img',
  '.product__image-link span img',
  'img.product-item__img',
  '.img_box img',
  '.grid-product__image',
  '.category-products-image',
  '.category-products-image[style*="background-image"]',
  '.image img',
  'img.img-responsive',
  ".product_image img",
  '.swiper-slide img',
  ".ndImage source[srcset]",
  ".picture a img",
  "[poster]",
  "[first-poster]",
  ".div.picture a img",
  "[data-secondary-image-src]",
  ".image-box [data-srcset]",
  ".pz-image-placeholder source[data-srcset]",
  "[data-lazy-bgset-src]",
  "[data-bgset]",
  ".product-secondary-image",
  "[data-image-src]",
  ".ndImage",
  "[data-img]",
  "img.product-image",
  ".PImage",
  "[data-srcset]",
  ".product-item-image",
  "[data-src]",
  ".d-block source",
  "[srcset]",
  "[data-original]",
  ".product-image-item",
  "[data-lazysrc]",
  "span.lazy-load-image-background [srcset]"


]
