export default [
    'a.carousel-item-container',
    '.cta-link-primary.product-card-v2-anchor',
    '[class^="style_productCard"] a.block',
    '.react-multi-carousel-item a',
    '.js-product-images-wrapper',
    'a.fast-filters-image-link',
    'a.product-item__info-name',
    '.product-tile-body__link',
    'a.item-img.swiper-slide',
    '.ltb__product--info-area > a:nth-child(1)',
    '.js-product-wrapper a',
    'a.image',
    'name a',
    ".grid-product__link",
    "a[data-cc-animate-click]",
    ".product-image-wrapper a",
    ".m-productCard__detail h3 > :nth-child(2)",
    ".product-figure-wrap a",
    "a.product-figure",
    "a.prd-link",
    "a.item-main-photo",
    "a[data-product]",
    ".product-image a",
    "a.image-wrapper",
    "a.product-figure",
    "a.product-link",
    ".product-name a",
    ".PrdImgsBox a",
    ".product__grid__info a",
    ".product-image a",
    "div.carousel-item a",
    "a.product-name",
    "product__grid__info a",
    "div.product-info a",
    "a.detailLink.detailUrl",
    ".product_image a"

]