export default [
    '.product-item__info-price',
    '.base-price.campaing-base-price',
    '.base-price.lined-base-price',
    '.first-line .base-price',
    '.product__price.-actual.h4',
    '.product__price.h5.-label.-old.-size',
    '.discountPrice .discountPriceSpan',
    '.regularPrice .regularPriceSpan',
    '.price .price__new',
    '.price.price--discounted .price__old',
    '.showcase-price-new',
    '.showcase-price-old',
    '.price-list .h6.text-on-sale',
    '.PriceArea .PPrice',
    '.price-list .h6.text-subdued',
    '.info .product-discounted-price',
    '.price__previous_mobile.product-list-price',
    '.prices_mobile_custom .product-sale-price',
    '.mainFiyat span',
    '.mainFiyat .fiyat',
    '.priceWrapper .currentPrice',
    '.text-line.discountedPrice.pr',
    '.current-price.fw-semibold',
    '.product-discounted-price.text-black.fw-regular',
    '.price .salesprice',
    '.price .old',
    '.price .amount',
    '.product__grid__price  .price',
    '.money.conversion-bear-money',
    '.price .salesprice',
    '.price .old',
    '.product__price.-actual.h4',
    '.product__campaignFeaturedArea.-seperated',
    '.product__price.h5.-label.-old.-size',
    '.product-price .oneprice',
    '.product-price .newprice.red',
    '.product-price .oldprice'
]