export default [
    '.product-item__info-price',
    '.base-price.campaing-base-price',
    '.base-price.lined-base-price',
    '.first-line .base-price',
    '.product__price.-actual.h4',
    '.product__price.h5.-label.-old.-size',
    '.discountPrice .discountPriceSpan',
    '.regularPrice .regularPriceSpan',
    '.price .price__new',
    '.price.price--discounted .price__old',
    '.showcase-price-new',
    '.showcase-price-old',
    '.price-list .h6.text-on-sale',
    '.PriceArea .PPrice',
    '.price-list .h6.text-subdued',
    '.info .product-discounted-price',
    '.price__previous_mobile.product-list-price',
    '.prices_mobile_custom .product-sale-price',
    '.mainFiyat span',
    '.mainFiyat .fiyat',
    '.priceWrapper .currentPrice',
    '.text-line.discountedPrice.pr',
    '.current-price.fw-semibold',
    '.product-discounted-price.text-black.fw-regular',
    '.price .salesprice',
    '.price .old',
    '.price .amount',
    '.product__grid__price  .price',
    '.money.conversion-bear-money',
    '.price .salesprice',
    '.price .old',
    '.product__price.-actual.h4',
    '.product__campaignFeaturedArea.-seperated',
    '.product__price.h5.-label.-old.-size',
    '.product-price .oneprice',
    '.product-price .newprice.red',
    '.product-price .oldprice',
    '.productPrice  .lastprice',
    '.ProductItem__Price.Price.Text--subdued',
    '.urunListe_satisFiyat',
    '.product-current-price .price',
    '.product-old-price .discounted-price',
    'div.flex.flex-wrap.items-center.gap-2 span.text-primary',
    '.product-price-content .product-new-price',
    '.product-price-content .product-old-price',
    '.price.actual-price',
    '.setrowSepetKategori.in2 span',
    '.product-price-wrapper .cart-discount',
    '.product-price-wrapper .current-price',
    '.prc.prc-last',
    '.prc.prc-first',
    '.productPrice .newPrice',
    '.productPrice .oldPrice',
    '.m-productCard__newPrice',
    '.m-productCard__oldPrice'
]