export default [
    '.product-item__info-price',
    '.base-price.campaing-base-price',
    '.base-price.lined-base-price',
    '.first-line .base-price',
    '.product__price.-actual.h4',
    '.product__price.h5.-label.-old.-size',
    '.discountPrice .discountPriceSpan',
    '.regularPrice .regularPriceSpan',
    '.price .price__new',
    '.price.price--discounted .price__old',
    '.showcase-price-new',
    '.showcase-price-old',
    '.price-list .h6.text-on-sale',
    '.PriceArea .PPrice',
    '.price-list .h6.text-subdued',
    '.info .product-discounted-price',
    '.price__previous_mobile.product-list-price',
    '.prices_mobile_custom .product-sale-price',
    '.mainFiyat span',
    '.mainFiyat .fiyat',
    '.priceWrapper .currentPrice',
    '.text-line.discountedPrice.pr',
    '.current-price.fw-semibold',
    '.product-discounted-price.text-black.fw-regular',
    '.price .salesprice',
    '.price .old',
    '.price .amount',
    '.product__grid__price  .price',
    '.money.conversion-bear-money',
    '.price .salesprice',
    '.price .old',
    '.product__price.-actual.h4',
    '.product__campaignFeaturedArea.-seperated',
    '.product__price.h5.-label.-old.-size',
    '.product-price .oneprice',
    '.product-price .newprice.red',
    '.product-price .oldprice',
    '.productPrice  .lastprice',
    '.ProductItem__Price.Price.Text--subdued',
    '.urunListe_satisFiyat',
    '.product-current-price .price',
    '.product-old-price .discounted-price',
    'div.flex.flex-wrap.items-center.gap-2 span.text-primary',
    '.product-price-content .product-new-price',
    '.product-price-content .product-old-price',
    '.price.actual-price',
    '.setrowSepetKategori.in2 span',
    '.product-price-wrapper .cart-discount',
    '.product-price-wrapper .current-price',
    '.prc.prc-last',
    '.prc.prc-first',
    '.productPrice .newPrice',
    '.productPrice .oldPrice',
    '.m-productCard__newPrice',
    '.m-productCard__oldPrice',
    '.money.buckscc-money',
    '.product__listing--basket-price',
    '.lone-price',
    '.product__listing--price del',
    'pz-price',
    '.product-card-v2-price__current',
    '[itemprop="priceCurrency"]',
    '[itemprop="highPrice"]',
    '[data-ge-price="data-ge-price"]',
    '.product-price .product-sale-price',
    '.product-price .product-list-price',
    '.product-price .price',
    '.old-price',
    '.discounted-price',
    '.product__listing--basket-price span',
    '.product-item__price pz-price',
    '.second-price',
    '.first-price',
    '.sell-price',
    '.current-price',
    '.KatSepetFiyat span',
    '[data-testid="product-price"]',
    'sale-price',
    '.current-price .product-price',
    '.product-discounted-price',
    '.price .price-normal',
    '.ac-pc__price',
    '.ac-pc__price.-retail',
    '.current-price .product-price',
    '.product-discounted-price',
    '.product-card__prices',
    '.product-item__basket-offers-price',
    '.color-primary font-financier-bold',
    '.product-item__price',
    '.p-wrap span.price',
    '.text-sm.font-semibold',
    '.product-item__price .money',
    '[doubly-currency="TRY"]',
    '.price .price-new',
     '.price .price-old',
     '.sepette-indirim .prom-fiyat',
     '.prices  .sale-price.line',
     '.grid-product__price span',
     '.product-price-wrapper .current-price',
     '.product-discounted-price',
     '.current-price .product-price',
     '.discount-price span:nth-child(2)',
     '.discount-price span:nth-child(1)',
     '.sale .money',
     '.t-subdued .money',
     '.price-item.price-item--sale.price-item--last',
     '.price-item.price-item--regular'


]