export default [
    '.js-product-list-item',
    '.list-content-product-item',
    '.ant-col.grid-item',
    '.item-box .product-item',
    '.productItemLayout',
    '.react-multi-carousel-item',
    'article.product-tile__plp',
    '.product-layout',
    "ac-product-card",
    "div.item .p-wrap",
    ".grid-product__content",
    ".category__list__main div.grid a",
    "li.product",
    ".product_box",
    ".MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-6.MuiGrid-grid-sm-6.MuiGrid-grid-md-4.MuiGrid-grid-lg-4", //yargıcı
    ".product-list .pitem",
    "[data-index].product-item",//gustoeshop
    ".product-item-box",
    ".products__item",
    ".productItem",
    ".showcase",
    ".Prd",
    ".product-list-item",
    ".product-card",
    ".product-grid-item",
    ".product-block",
    ".Prd",
    ".ProductItem__Wrapper",
    ".prd",
    ".prod-card",
    ".max-w-xl.fade-in",
    ".productCartMain",
    ".prd-link",
    "[class^='ProductCard_productCard']",
    ".o-productList__itemWrapper",
    ".product-layout",
    ".col-md-3.col-sm-3.col-xs-6.wow",
    ".product-grid-container .grid__item",
    ".js-product-list-item",
    ".product-listing-shelf__product-card",
    ".divUrun",
    //".grid-item",
    ".js-product-wrapper.product-item",
    ".c-product-grid__item",
    "legacy-product",
    "article[data-category]",
    ".productItemLayout.ViewProduct",
    // ".grid [data-id]",
    ".js-product-item",
    ".product",
    "[data-testid='product-box']",
    ".scroll-product-item",
    "ac-product-card",
    ".products-list__item",
    //".item",
    ".js-list-content-product-item",
    ".product_item",
    ".relative.flex.h-full.w-full.grow.flex-col",
    //".grid__item",
    ".card-product",
    //"div[data-id]",
    // "[data-id]",
    ".product-list__item",

]