export default [
    'h2[class^="productcard_type1_product_card1_title"]',
    'h3.ac-pc__name a',
    'a.product-info-detail',
    'div.product-item__name',
    'a.image img',
    '.name a',
    'a.image img',
    "a.image",
    "h1.pro_name a",
    ".text-left.text-sm.font-medium.text-button-01",
    'div.caption div.name a',
    ".grid-product__title",
    "h2.product-name",
    ".product-item__product-title a",
    "a.custom-card-title",
    "a span.title",
    "h3.product-name",
    '.mfn-woo-product-title a',
    ".product_image img",
    ".m-productCard__desc",
    "div.mainTitle",
    "h2 .js-product-link.product-link",
    "h3.text-primary a.inline-block.line-clamp-2",
    ".product-name a",
    "a.product-item__name",
    "a.product-title",
    "span.PName", "a.product-name",
    ".personaclick-recommender-description a div",
    ".mainTitle[title]",
    ".product-title a",
    "p.product__grid__title",
    ".product-block__title",
    ".ProductItem__Title.Heading a",
    "div.product-name",
    ".productName a",
    ".prd-title h2",
    ".product-title .title h3",
    // ".product-image-desktop",

    // ".mainTitle",
    // ".productName.detailUrl a",
    // ".product-name",
    // ".product-card__title--name",

    // ".product-item__name",
    // ".product-title",
    // ".PName",
    // ".product-name"
    "a[title]:not([href='javascript:void(0);'] :not([href='#']):not([href=''])"

]