export default [
  'wow-image img',
  '.showcase-image img',
  '.product-list-item-thumbnail img',
  "document.querySelector('.attachment-woocommerce_thumbnail').getAttribute('data-lazy-src')",
  'img.attachment-woocommerce_thumbnail',
  '.product-item-img',
  '.main-product-img.card-img',
  'span.teaser img',
  '.tp-image img',
  "[data-testid='next-image'] img",
  '[id^="product_image"] .lazy-image img',
  '.product-grid__image',//guess
  'img.productSliderImage',
  '[imagetype="PRODUCT_IMAGE"]',
  'img.image-responsive',
  'picture.media-carousel-container__media source',
  'img.media-carousel-container__media',
  'img.swiper-slide',
  '.media-carousel-container__media.product-card-v2-carousel-container__media__source',
  '.product-tile-image__picture source',
  '.lazy-load-image-background img.w-full',
  'img.category-products-image',
  '.image-inner img',
  '.ltb__product--image',
  '.product-image__img',
  '.product__image-link span img',
  'img.product-item__img',
  '.img_box img',
  '.grid-product__image',
  '.category-products-image',
  '.category-products-image[style*="background-image"]',
  '.image img',
  'img.img-responsive',
  ".product_image img",
  '.swiper-slide img',
  ".ndImage source[srcset]",
  ".picture a img",
  "[poster]",
  "[first-poster]",
  ".div.picture a img",
  "[data-secondary-image-src]",
  ".image-box [data-srcset]",
  ".pz-image-placeholder source[data-srcset]",
  "[data-lazy-bgset-src]",
  "[data-bgset]",
  ".product-secondary-image",
  "[data-image-src]",
  ".ndImage",
  "[data-img]",
  "img.product-image",
  ".PImage",
  "[data-srcset]",
  ".product-item-image",
  "[data-src]",
  ".d-block source",
  "[srcset]",
  "[data-original]",
  ".product-image-item",
  "[data-lazysrc]",
  "span.lazy-load-image-background [srcset]",

]
