export default [
    '.category-product-count.mb-2.d-none.d-md-block',
    '.collection-filter__item--count',
    '.collection-toolbar__products-count',
    'span.text-primary',
    '.filtreurun b',
    '.Urad span',
    '.list__count',
    '.headline-product-count',
    '.pager-area .total-product',
    '.prd-qty', '.prd-qty span',
    '.plp-info.js-plp-info',
    '#ProductCount',
    '.UrunAdet',
    '.FiltrelemeUrunAdet span',
    '.text-center.text-gray.mb-2',
    '.mobil-count',
    '.collection__products-count',
    'h1 span',
    '.boost-sd__product-count',
    'h3.category-title span',
    '.appliedFilter.FiltrelemeUrunAdet span',
    '.search-total-count',
    '.algolia-plp__products-stats',
    '.entity__count span',
    '.js-result-count',
    'span.entity__count',
    '.items-total',
    '.products-count-wrapper span',
    '.product-count-text',
    '.o-productList__top--breadcrumbCount',
    '.catalog__meta--product-count span',
    '.list__product-count',
    '.products-listed',
    '.countProductSection span',
    '.list-title-count',
    '.load-more__info-text-product-count',
    'span#ProductCount',
    '.product-list-total span',
    'span.counter',
    '.product-list-filter-count',
    "[data-js='product-count']",
    "[data-testid='list-count']",
    '.js-total-products-count',
    '.TotalProductCount',
    '.category-title',
    '.search-total-count span',
    '.product-count__text',
    '.woocommerce-result-count',
    '.total-product span',
    "[data-element='plp-product-count']",
    '#ProductCountDesktop',
    '.product-info-bar span']