export default [
    '[class*="style_price__"]',
    '.item-price',
    '.woocommerce-Price-amount.amount',
    '.priceone',
    '[data-hook="product-item-price-to-pay"]',
    'span.new-price',
    '.product-list-item-price .money',
    '.money.buckscc-money',
    '.price-item.price-item--regular',
    '.product-prices li.text-left',
    '.rvts-badge-discount p',
    '.para-tutar',
    'span.text-sm.font-bold.leading-snug.text-primary',
    '.item-price.textBase',
    // Shadow DOM selectors - highest priority for price-element
    'price-element::shadow::.price-container .price',
    'price-element::shadow::.price',
    'price-element::shadow::div.price',
    'price-element::shadow::.container .price',
    'document.querySelector("price-element").shadowRoot.querySelector(".price-container .price")',
    'document.querySelector("price-element").shadowRoot.querySelector(".price")',
    'document.querySelector("price-element").shadowRoot.querySelector("div.price")',
    'document.querySelector("price-element").shadowRoot.querySelector(".container .price")',

    // Existing shadow DOM selectors from your original file
    'document.querySelector("price-element").shadowRoot.querySelector(".container .price");',
    '.product-info price-element::shadow::.price',

    // Your existing regular selectors
    '.product-box-new-price',
    'span.product-box-price',
    '[class*="SinglePrice_"]',
    '.pricebox .oneprice',
    '.pricebox .newprice',
    '.tp-price-number',
    '.grid-product__price--original',
    'document.querySelector(".grid-product__price").childNodes[5].textContent.trim();',
    '.current-price.promotion-current-price',
    '.price__regular span:nth-child(2)',
    '.product--price .money',
    '.product-item__price .wd_discount',
    'span.wpDiscountPriceBlock',
    'product-price .price',
    'span.product-price',
    '.product-pricing .price',
    '.product-pricing .nodiscount-price',
    '[data-testid="product-price"]',
    'formatted-price-detail div div',
    '.product-grid-item__price .h-11',//derimod
    '.product-grid-item__price__new',//derimod
    '.boost-sd__format-currency',
    '.boost-sd__product-price--sale .boost-sd__format-currency',
    '.product_box .price',
    '.product-item-info-prices .product-sale-price',
    'spa-product-price .price',
    '.product-card__price--new',
    '.p-price .one-price',
    'span.value.item-price',
    '.value.item-price.txt-bold',
    '.product-price__list-price',
    '.product-price__sales-price',//jackjones
    '.price--wrap div.new--price',//ltbjeans
    'span.divUFiyat1',//buenoshoes
    '.mainFiyat .mainFiyat2',
    '.second-line .base-price:not(.campaing-base-price)',//defacto
    '.first-line .base-price:not(.campaing-base-price)',//defacto
    '.base-price.lined-base-price',
    '.product__price.-actual.h4',
    '.product__price.h5.-label.-old.-size',
    '.discountPrice .discountPriceSpan',
    '.regularPrice .regularPriceSpan',
    '.price .price__new',
    '.price.price--discounted .price__old',
    '.showcase-price-new',
    '.showcase-price-old',
    '.price-list .h6.text-on-sale',
    '.PriceArea .PPrice',
    '.price-list .h6.text-subdued',
    '.info .product-discounted-price',
    '.price__previous_mobile.product-list-price',
    '.prices_mobile_custom .product-sale-price',
    '.mainFiyat span',
    '.mainFiyat .fiyat',
    '.priceWrapper .currentPrice',
    '.text-line.discountedPrice.pr',
    '.current-price.fw-semibold',
    '.product-discounted-price.text-black.fw-regular',
    '.price .salesprice',
    '.price .old',
    '.price .amount',
    '.product__grid__price  .price',
    '.money.conversion-bear-money',
    '.price .old',
    '.product__price.-actual.h4',
    '.product__campaignFeaturedArea.-seperated',
    '.product__price.h5.-label.-old.-size',
    '.product-price .oneprice',
    '.product-price .newprice.red',
    '.product-price .oldprice',
    '.productPrice  .lastprice',
    '.ProductItem__Price.Price.Text--subdued',
    '.urunListe_satisFiyat',
    '.product-current-price .price',
    '.product-old-price .discounted-price',
    'div.flex.flex-wrap.items-center.gap-2 span.text-primary',
    '.product-price-content .product-new-price',
    '.product-price-content .product-old-price',
    '.price.actual-price',
    '.setrowSepetKategori.in2 span',
    '.product-price-wrapper .cart-discount',
    '.product-price-wrapper .current-price',
    '.prc.prc-last',
    '.prc.prc-first',
    '.productPrice .newPrice',
    '.productPrice .oldPrice',
    '.m-productCard__newPrice',
    '.m-productCard__oldPrice',
    '.money.buckscc-money',
    '.product__listing--basket-price',
    '.lone-price',
    '.product__listing--price del',
    'pz-price',
    '.product-card-v2-price__current',
    '[itemprop="highPrice"]',
    '[data-ge-price="data-ge-price"]',
    '.product-price .product-sale-price',
    '.product-price .product-list-price',
    '.product-price .price',
    '.old-price',
    '.discounted-price',
    '.product__listing--basket-price span',
    '.product-item__price pz-price',
    '.second-price',
    '.first-price',
    '.sell-price',
    '.current-price',
    '.KatSepetFiyat span',
    'sale-price',
    '.current-price .product-price',
    '.product-discounted-price',
    '.price .price-normal',
    '.ac-pc__price',
    '.ac-pc__price.-retail',
    '.current-price .product-price',
    '.product-discounted-price',
    '.product-card__prices',
    '.product-item__basket-offers-price',
    '.color-primary font-financier-bold',
    '.p-wrap span.price',
    '.text-sm.font-semibold',
    '.product-item__price .money',
    '[doubly-currency="TRY"]',
    '.price .price-new',
    '.price .price-old',
    '.sepette-indirim .prom-fiyat',
    '.prices  .sale-price.line',
    '.grid-product__price > :not(.visually-hidden)',
    '.product-price-wrapper .current-price',
    '.product-discounted-price',
    '.current-price .product-price',
    '.discount-price span:nth-child(2)',
    '.discount-price span:nth-child(1)',
    '.sale .money',
    '.t-subdued .money',
    '.price-item.price-item--sale.price-item--last',
    '.price-item.price-item--regular',
    '.price .theme-money',
    '.product-pricing-one__price',
    '.product-pricing-two span',
    '.woocommerce-Price-amount.amount',
    '.sale-price-basket .sale-price',
    '.price.price-box .price-sales',
    '.woocommerce-Price-amount.amount bdi',
    '[data-articlecode] div div p span',
    '.productPrice .discountPrice',
    '.productPrice .regularPrice',
    '.product-price-content .product-sale-price',
    '[class^="product_card_product_price"]',
    '[class^="product_card_product_old_price"]',
    'span.product-item-campaign-price',
    '.product-item-price-wrapper-list .product-item__price.color-primary',
    '.product-item-price-wrapper .color-primary.font-financier-bold',
    '.product-price-content .product-price',
    '.price',
    '.price-container .price'
]