export default [
  '.content-product-card .product-media:has(product-prices)',
    '.product-list__products article.product-tile-core',
    '.content-product-card .product-media',
    '[data-product-id].product-block.none[data-cc-animate]',
    '[class*="style_product_container"]',
    '.list__content .js-product-wrapper.product-item',
    '#ProductPageProductList .ItemOrj .productItem',
    'li.grid__item .card-wrapper.product-card-wrapper:has(a)',
    '.list-item .list-item-inline',
    '.product_single',
    '[data-hook="product-list-grid-item"]',
    '.sf__pcard.cursor-pointer.sf-prod__block',
    'li.grid__item .card-wrapper.product-card-wrapper',
    'loess-product-card',
    '.product-box-container',
    '.single-banner',
    '.cat-product article.product-box:has(.product-body)',//
    '.c-tile.c-tile--product',
    '.product-grid-item-container .product-box-container',
    'li.virtual-item',
    'ozd-custom-product-grid-item .carouselItem',
    '.grid__item.grid-product.medium-up--one-half',
    '[id*=product-tile-wrapper-]',
    'ozd-custom-product-grid-item',
    '.product--root',
    '.productItem:not(:has(.pw-img-swiper))',// elleshoes //.productItem:not(.prd):not(:has(.pw-img-swiper))
    '.grid__item:has(.price)',
    '.text-sm.text-left.flex.flex-col',
    '.grid-product-list--4B .content-product-card',
    '.p-item-inside',
    '.test.MuiBox-root',
    '.ProductCard.mb-2.w-full',
    '.boost-sd__product-item',
    'article.product-tile-core',
    '.product_box.sm-product-list',
    '.infinite-scroll-component  .max-w-xl',
    '.p-item.col-6',
    'article.product-card',
    '.p-item.col',
    '.js-tile.product__tile',
    'article.product-tile__plp',
    '.ltb__product.js-gtm-impression',
    '.padding-lg.list-content-product-item',
    '.productCartMain',
    '[data-testid][class^="product_card_product_card"]',
    '.product-item',
    '.c-tiles-column',
    '[data-testid="product-box"]',
    '.js-product-list-item',
    '.list-content-product-item:has(.product-name a)',
    '.ant-col.grid-item',
    '.item-box .product-item',
    '.productItemLayout',
    '.react-multi-carousel-item',
    'article.product-tile__plp',
    '.product-layout',
    "ac-product-card",
    "div.item .p-wrap",
    ".grid-product__content",
    ".category__list__main div.grid a",
    "li.product",
    ".product_box",
    ".MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-6.MuiGrid-grid-sm-6.MuiGrid-grid-md-4.MuiGrid-grid-lg-4", //yargıcı
    ".product-list .pitem",
    ".pitem",
    ".pitem .piteminside",
    "[data-index].product-item",//gustoeshop
    ".product-item-box",
    ".products__item",
    ".productItem",
    ".showcase",
    ".Prd",
    ".product-list-item",
    ".product-card",
    ".product-grid-item",
    ".product-block",
    ".Prd",
    ".ProductItem__Wrapper",
    ".prd",
    ".prod-card",
    ".max-w-xl.fade-in:has(img)",
    ".productCartMain",
    ".prd-link",
    "[class^='ProductCard_productCard']",
    ".o-productList__itemWrapper",
    ".product-layout",
    ".col-md-3.col-sm-3.col-xs-6.wow",
    ".product-grid-container .grid__item",//causes problem for aldo
    ".js-product-list-item",
    ".product-listing-shelf__product-card",
    ".divUrun",
    ".grid-item",
    ".js-product-wrapper.product-item",
    ".c-product-grid__item",
    "legacy-product",
    "article[data-category]",
    ".productItemLayout.ViewProduct",
    ".grid [data-id]",
    ".js-product-item",
    ".product",
    "[data-testid='product-box']",
    ".scroll-product-item",
    "ac-product-card",
    ".products-list__item",
    ".item",
    ".js-list-content-product-item",
    ".product_item",
    ".relative.flex.h-full.w-full.grow.flex-col",
    "li.grid__item", //causes problem for aldo

    ".card-product",
    "div[data-id]",
    "[data-id]",
    ".product-list__item",

]