export default [
    '.product-item__title',
    '.product-list-item-title',
    '.woocommerce-loop-product__title',
    '.qodef-product-list-title a',
    '.woocommerce-loop-product__title a',
    'a.card__title',
    '.product__inside__name .product-shot-desc',
    '.product-title a',
    '.text-xs.font-medium.leading-snug.text-secondary-100',
    'span.productbox-name',
    '[class*="ProductTitle_"]',
    '.tp-body.product-title',
    '.product-item-info  p.product-name a',
    '.product-item-info a',
    '.product-card__link',
    'p.product--title',
    '[class*="__product_title_"] p',
    'a.product-item__name',//lcw
    '.product-description.product-card-info__description',
    'h3 a.block.text-primary.text-xs',
    'p.product-name',
    'h2.product-name',
    '.card-information__text.h4',
    '.product-title span',
    '.p-name a',
    '.product-content-name',
    '.product-grid-item__title',
    '.boost-sd__product-title',
    'h3.product-card__name',
    '.product-item-content__info h3',
    '.plp-card-title',
    '.js-aa-pdp-href.aa-pdp-href',
    '.entry-title.qode-pli-title a',
    'img.motion-reduce',
    'span.product-name',
    '.product-card-v2-title',
    '[class^="style_productCard"] p.name',
    'h2.product-item__name',
    'a .relative.inline-block.w-full img',
    'h2[class^="product_card_product_title"] a',
    '.product__listing--content h3 a',
    '.fast-filters-image-title',
    '.cta-link-primary.product-card-v2-anchor',
    'h2.product-card-v2-title',
    ".product-tile-info__title",
    '.product-item__info-product-name',
    'h3.product__name a',
    '.product-tile-body__link',
    'h3.product-name',
    '.product-name a',
    '.ltb__product--info-area > a:nth-child(2) h5',
    'h2[class^="productcard_type1_product_card1_title"]',
    'h3.ac-pc__name a',
    'a.product-info-detail',
    'div.product-item__name',
    'a.image img',
    '.name a',
    'a.image img',
    "a.image",
    "h1.pro_name a",
    ".text-left.text-sm.font-medium.text-button-01",
    'div.caption div.name a',
    ".grid-product__title",
    "h2.product-name",
    ".product-item__product-title a",
    "a.custom-card-title",
    "a span.title",
    "h3.product-name",
    '.mfn-woo-product-title a',
    ".product_image img",
    ".m-productCard__desc",
    "div.mainTitle",
    "h2 .js-product-link.product-link",
    "h3.text-primary a.inline-block.line-clamp-2",
    ".product-name a",
    "a.product-item__name",
    "a.product-title",
    "span.PName", "a.product-name",
    ".personaclick-recommender-description a div",
    ".mainTitle[title]",
    ".product-title a",
    "p.product__grid__title",
    ".product-block__title",
    ".ProductItem__Title.Heading a",
    "div.product-name",
    ".productName a",
    ".prd-title h2",
    ".product-title .title h3",
    // ".product-image-desktop",

    // ".mainTitle",
    // ".productName.detailUrl a",
    // ".product-name",
    // ".product-card__title--name",

    // ".product-item__name",
    // ".product-title",
    // ".PName",
    // ".product-name"
    "a[title]:not([href='javascript:void(0);']):not([href='#']):not([href=''])"

]